/*
 * TransferPanel.java
 *
 * Created on January 25, 2008, 2:03 PM
 */

package org.jini.projects.neon.ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.rmi.RMISecurityManager;
import java.rmi.RemoteException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

import net.jini.core.entry.Entry;
import net.jini.core.lookup.ServiceItem;
import net.jini.core.lookup.ServiceMatches;
import net.jini.core.lookup.ServiceRegistrar;
import net.jini.core.lookup.ServiceTemplate;
import net.jini.discovery.DiscoveryListener;
import net.jini.discovery.LookupDiscovery;
import net.jini.discovery.LookupDiscoveryManager;
import net.jini.lookup.entry.Name;
import net.jini.lookup.entry.ServiceInfo;

/**
 * 
 * @author calum
 */
public class TransferPanel extends javax.swing.JPanel {

	public static void main(String[] args) {
		System.setSecurityManager(new RMISecurityManager());

		JFrame jf = new JFrame();
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jf.setSize(800, 800);
		jf.setLayout(new BorderLayout());
		TransferPanel lookup = new TransferPanel();
		jf.add(lookup, BorderLayout.CENTER);
		jf.setVisible(true);
		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		lookup.doDiscovery();
	}

	private void doDiscovery() {
		// TODO Auto-generated method stub
		try {
			serviceDropDownModel.removeAllElements();
			LookupDiscoveryManager ld = new LookupDiscoveryManager(LookupDiscovery.ALL_GROUPS, null, discoveryListener);
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}

	/** Creates new form TransferPanel */
	public TransferPanel() {
		initComponents();
		jProgressBar1.putClientProperty("JProgressBar.style", "circular");
		jComboBox1.putClientProperty("JComboBox.isPopDown", Boolean.TRUE);
		jButton1.putClientProperty("JButton.buttonType", "bevel");
		jButton1.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				jProgressBar1.setVisible(true);
				doDiscovery();
			}
		});
		serviceDropDownModel = new DefaultComboBoxModel();
		jComboBox1.setModel(serviceDropDownModel);
		discoveryListener = new DiscoveryListener() {
			public void discarded(net.jini.discovery.DiscoveryEvent e) {
			};

			public void discovered(net.jini.discovery.DiscoveryEvent e) {
				System.out.println("Service Discovered");
				ServiceRegistrar[] regs = e.getRegistrars();
				for (int i = 0; i < regs.length; i++) {
					try {
						ServiceMatches matches = regs[i].lookup(new ServiceTemplate(null, null, null), 20);
						jLabel2.setText("Found: " + matches.totalMatches + " services");
						for (int j = 0; j < matches.items.length; j++) {
							ServiceItem item = matches.items[j];
							Entry[] attributes = item.attributeSets;
							String toAdd = item.service.getClass().getName();
							for (Entry attr : attributes) {
								if (attr instanceof Name) {
									toAdd = ((Name) attr).name;
									break;
								}
								if (attr instanceof ServiceInfo)
									toAdd = ((ServiceInfo) attr).name;
							}
							serviceDropDownModel.addElement(toAdd);
							
						}
					} catch (RemoteException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
				jProgressBar1.setVisible(false);
			};
		};
		

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Select Service:");

        jProgressBar1.setIndeterminate(true);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("Searching...");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Refresh");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(4, 4, 4)
                                .add(jLabel2)
                                .add(35, 35, 35)
                                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(6, 6, 6)
                                .add(jButton1)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jLabel2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
	private DefaultComboBoxModel serviceDropDownModel;
	private DiscoveryListener discoveryListener;

}
