/*
 * NewAgentPanel.java
 *
 * Created on 14 November 2005, 17:53
 */

package org.jini.projects.neon.service.admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.rmi.RMISecurityManager;
import java.rmi.RemoteException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

import org.jini.projects.neon.util.AgentDeployLauncher;
import org.jini.projects.neon.util.AgentDeployer;
import org.jini.projects.neon.service.AgentService;

import org.jini.projects.neon.service.admin.DomainDescription;
import org.jini.projects.neon.service.admin.AgentAdmin;

/**
 * 
 * @author Calum
 */
public class NewAgentPanel extends javax.swing.JPanel {

	DefaultComboBoxModel domainModel = new DefaultComboBoxModel();
	private AgentServiceAdmin svcAdmin;

	private AgentService svc;

	/** Creates new form NewAgentPanel */
	public NewAgentPanel() {
		initComponents();
		useAgentDeploy.setSelected(true);
		toggleDeployDetails(true);
		locateJarFile.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				showFileChooser();
			}
		});

	}

	public NewAgentPanel(AgentService svc) {
		this();
		this.svc = svc;
		try {
			this.svcAdmin = (AgentServiceAdmin) svc.getAdmin();

			DomainDescription[] descs = svcAdmin.getDomains();
			for (int i = 0; i < descs.length; i++)
				domainModel.addElement(descs[i].getName());
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		System.setSecurityManager(new RMISecurityManager());
		JFrame jf = new JFrame();
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jf.setSize(300, 500);
		jf.getContentPane().add(new NewAgentPanel());
		jf.setVisible(true);
	}

	public void showFileChooser() {
		JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
		FileFilter filter = new FileFilter() {

			public boolean accept(File f) {
				// TODO Auto-generated method stub
				if (f.getAbsolutePath().endsWith(".jar"))
					return true;
				if (f.isDirectory())
					return true;
				return false;
			}

			public String getDescription() {
				// TODO Auto-generated method stub
				return "Java Archive Files (*.jar)";
			}
		};
		chooser.setMultiSelectionEnabled(true);
		chooser.setFileFilter(filter);
		int option = chooser.showOpenDialog(this);
		if (option == JFileChooser.APPROVE_OPTION) {
			StringBuffer buffer = new StringBuffer(jarFile.getText());
			File[] files = chooser.getSelectedFiles();
			if (jarFile.getText().trim().length() > 0)
				buffer.append(File.separatorChar);
			for (int i = 0; i < files.length; i++) {

				buffer.append(files[i].getAbsolutePath());
				if (i != files.length - 1)
					buffer.append(";");
			}

			jarFile.setText(buffer.toString());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		deployButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		agentClassName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		configurationURL = new javax.swing.JTextField();
		constraintsFile = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		chosenDomain = new javax.swing.JComboBox();
		useAgentDeploy = new javax.swing.JCheckBox();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jarFile = new javax.swing.JTextField();
		codebase = new javax.swing.JTextField();
		group = new javax.swing.JTextField();
		serviceID = new javax.swing.JTextField();
		locateJarFile = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		seedingLocation = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel1.setText("Deploy New Agent   ");
		jLabel1.setAlignmentX(0.1F);
		jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabel1.setOpaque(true);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		deployButton.setText("Deploy");
		deployButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deployButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancel");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(327, Short.MAX_VALUE).add(deployButton).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(cancelButton).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().addContainerGap().add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(deployButton).add(cancelButton)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)));

		jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setText("Agent ClassName:");

		jLabel3.setText("Configuration URL:");

		jLabel4.setText("Constraints File:");

		jLabel5.setText("Place in Domain:");

		chosenDomain.setModel(domainModel);

		useAgentDeploy.setText("Use Agent Deployer (req. Security permissions)");
		useAgentDeploy.setMargin(new java.awt.Insets(0, 0, 0, 0));
		useAgentDeploy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				toggleAgentDeploy(evt);
			}
		});

		jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel6.setText("Jar File");

		jLabel7.setText("Codebase");

		jLabel8.setText("Group");

		jLabel9.setText("ServiceID");

		locateJarFile.setText("...");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jLabel7).add(jLabel6).add(jLabel8).add(jLabel9)).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(codebase, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE).add(group, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352,
								Short.MAX_VALUE).add(serviceID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE).add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								jPanel2Layout.createSequentialGroup().add(jarFile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(locateJarFile,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel6).add(locateJarFile).add(jarFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel7).add(codebase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel8).add(group, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(11, 11, 11).add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel9).add(serviceID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel3Layout.createSequentialGroup().add(
						jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
								jPanel3Layout.createSequentialGroup().add(24, 24, 24).add(jLabel2).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(agentClassName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)).add(
								jPanel3Layout.createSequentialGroup().addContainerGap().add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jLabel4).add(jLabel3).add(jLabel5)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(chosenDomain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
												org.jdesktop.layout.GroupLayout.TRAILING, configurationURL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE).add(org.jdesktop.layout.GroupLayout.TRAILING, constraintsFile,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))).add(jPanel3Layout.createSequentialGroup().addContainerGap().add(useAgentDeploy)).add(
								jPanel3Layout.createSequentialGroup().addContainerGap().add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel3Layout.createSequentialGroup().addContainerGap().add(
						jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2).add(agentClassName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(configurationURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jLabel3)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel4).add(constraintsFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel5).add(chosenDomain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(useAgentDeploy).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(jPanel2,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(134, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Single Agent", jPanel3);

		jLabel10.setText("Location URL:");

		jButton1.setText("Browse For Local File");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 10));
		jLabel11
				.setText("<html><b>Seeding Files</b><br> A Seeding file allows you to deploy multiple agents in one go and is of the form:<br> <pre> &lt;seeding&gt;\n    &lt;agents&gt;\n        &lt;agent&gt;\n            &lt;classname&gt;&lt;/classname&gt;\n            &lt;configurl&gt;&lt;/configurl&gt;\n            &lt;constraintsurl&gt;&lt;/constraintsurl&gt;\n            &lt;domain&gt;&lt;/domain&gt;\n            &lt;codebase&gt;&lt;/codebase&gt;\n        &lt;/agent&gt;\n    &lt;/agents&gt;\n&lt;/seeding&gt;> </pre> </html>");

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel4Layout.createSequentialGroup().addContainerGap().add(
						jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jButton1).add(
								jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jLabel11).add(
										jPanel4Layout.createSequentialGroup().add(jLabel10).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(seedingLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))).addContainerGap(23, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel4Layout.createSequentialGroup().add(26, 26, 26).add(
						jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel10).add(seedingLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton1).add(18, 18, 18).add(jLabel11).addContainerGap(135, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Seeding File", jPanel4);

		jLabel12.setText("Location URL:");

		jButton2.setText("Browse For Local File");

		jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 10));
		jLabel13
				.setText("<html><b>Neon Archives</b><br>  Neon Archives work like Seeding files, but are a special codebase file,<br>containing not only all the classes to deploy the agents, but also: <br> <ul> <li>An extended seeeding file, with information regarding slices</li> <li>Slice definitions</li> </ul> </html>");

		org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel5Layout.createSequentialGroup().addContainerGap().add(
						jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jButton2).add(
								jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jLabel13).add(
										jPanel5Layout.createSequentialGroup().add(jLabel12).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))).addContainerGap(72, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel5Layout.createSequentialGroup().add(26, 26, 26).add(
						jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel12).add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton2).add(18, 18, 18).add(jLabel13).addContainerGap(249, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Neon Archive", jPanel5);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE).add(
				layout.createSequentialGroup().addContainerGap().add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE).addContainerGap()).add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(jTabbedPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE).add(4, 4, 4).add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>//GEN-END:initComponents

	private void deployButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deployButtonActionPerformed
		// TODO add your handling code here:
		if (jTabbedPane1.getSelectedIndex() == 1) {
			System.out.println("Seeding Tab");
			File f = new File(seedingLocation.getText());
			SeedingHandler handler = new SeedingHandler(f);
			for (SeedingAgentDetails detail : handler.getAgentDetailList())
				new AgentDeployer(detail, svc);

		} else
			doDeploy();
	}// GEN-LAST:event_deployButtonActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		JFileChooser myChooser = new JFileChooser();
		myChooser.setDialogTitle("Open Seeding file");
		myChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		myChooser.setFileFilter(new FileFilter() {

			@Override
			public boolean accept(File f) {
				if (f.isDirectory())

					return true;
				if (f.getAbsolutePath().endsWith(".xml"))
					return true;
				return false;
			}

			@Override
			public String getDescription() {
				return "XML Files";
			}
		});
		myChooser.showOpenDialog(this);
		seedingLocation.setText(myChooser.getSelectedFile().getAbsolutePath());

	}// GEN-LAST:event_jButton1ActionPerformed

	private void toggleAgentDeploy(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_toggleAgentDeploy
		// TODO add your handling code here:

		toggleDeployDetails(useAgentDeploy.isSelected());
	}// GEN-LAST:event_toggleAgentDeploy

	private void toggleDeployDetails(boolean setValue) {
		this.jarFile.setEnabled(setValue);
		this.locateJarFile.setEnabled(setValue);
		this.group.setEnabled(setValue);
		this.serviceID.setEnabled(setValue);
		this.codebase.setEnabled(setValue);
	}

	private void doDeploy() {
		if (useAgentDeploy.isSelected()) {
			String agentClass = agentClassName.getText();
			String domain = (String) chosenDomain.getSelectedItem();
			String codeBase = codebase.getText();
			String configuration = configurationURL.getText();
			String constraints = constraintsFile.getText();
			String serviceid = serviceID.getText();
			String jinigroup = group.getText();
			String jar = jarFile.getText();
			System.out.println("Deploying......");
			AgentDeployer deploy = new AgentDeployer(agentClass, configuration, constraints, codeBase, jar, jinigroup, serviceid);

		} else
			JOptionPane.showMessageDialog(this, "Unsupported at the moment please select to use AGentDeployer instead", "Warning", JOptionPane.ERROR_MESSAGE);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JTextField agentClassName;
	public javax.swing.JButton cancelButton;
	public javax.swing.JComboBox chosenDomain;
	public javax.swing.JTextField codebase;
	public javax.swing.JTextField configurationURL;
	public javax.swing.JTextField constraintsFile;
	public javax.swing.JButton deployButton;
	public javax.swing.JTextField group;
	public javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel10;
	public javax.swing.JLabel jLabel11;
	public javax.swing.JLabel jLabel12;
	public javax.swing.JLabel jLabel13;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JLabel jLabel6;
	public javax.swing.JLabel jLabel7;
	public javax.swing.JLabel jLabel8;
	public javax.swing.JLabel jLabel9;
	public javax.swing.JPanel jPanel1;
	public javax.swing.JPanel jPanel2;
	public javax.swing.JPanel jPanel3;
	public javax.swing.JPanel jPanel4;
	public javax.swing.JPanel jPanel5;
	public javax.swing.JTabbedPane jTabbedPane1;
	public javax.swing.JTextField jTextField2;
	public javax.swing.JTextField jarFile;
	public javax.swing.JButton locateJarFile;
	public javax.swing.JTextField seedingLocation;
	public javax.swing.JTextField serviceID;
	public javax.swing.JCheckBox useAgentDeploy;
	// End of variables declaration//GEN-END:variables

}
