/*
 * VertigoManager.java
 *
 * Created on 05 October 2007, 15:40
 */

package org.jini.projects.neon.vertigo.management.ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

import org.jdesktop.layout.GroupLayout;

/**
 * 
 * @author calum
 */
public class VertigoManager extends javax.swing.JPanel {

	DefaultTreeModel model;

	/** Creates new form VertigoManager */
	public VertigoManager() {
		DefaultMutableTreeNode node = new DefaultMutableTreeNode(new SliceData("Application", SliceData.APPLICATION));
		model = new DefaultTreeModel(node);
		initComponents();
		jComboBox1.setRenderer(new SliceComboListRenderer());
		addSliceButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				addSlice();
			}
		});
		jComboBox1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (jTree1.getSelectionPath() != null) {
					SliceData dat = (SliceData) ((DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent()).getUserObject();
					dat.setType((String) jComboBox1.getSelectedItem());
					jTree1.updateUI();
				}
			}
		});
		jTree1.addTreeSelectionListener(new TreeSelectionListener() {
			public void valueChanged(TreeSelectionEvent e) {
				DefaultMutableTreeNode node = (DefaultMutableTreeNode) e.getPath().getLastPathComponent();
				final SliceData dat = (SliceData) node.getUserObject();
				SwingUtilities.invokeLater(new Runnable() {
					public void run() {
						// TODO Auto-generated method stub
						jComboBox1.setSelectedIndex(dat.getType());
						name.setText(dat.getName());
					}
				});
				// name.setText(dat.getName());
			}
		});
	

		name.addKeyListener(new KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent e) {
				DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
				final SliceData dat = (SliceData) node.getUserObject();
				dat.setName(name.getText());
				SwingUtilities.invokeLater(new Runnable() {
					public void run() {
						jTree1.updateUI();
					}
				});

			}
		});

	}

	public void addSlice() {
		DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
		node.add(new DefaultMutableTreeNode(new SliceData(JOptionPane.showInputDialog("Name for Slice:"), SliceData.DEFAULT)));
		TreePath selectedPath = jTree1.getSelectionPath();
		jTree1.expandPath(selectedPath);
		jTree1.setSelectionPath(selectedPath);
		jTree1.updateUI();
	}

	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		JFrame jf = new JFrame("Sample Form");
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jf.setSize(200, 400);
		jf.getContentPane().setLayout(new BorderLayout());
		jf.getContentPane().add(new VertigoManager(), BorderLayout.CENTER);
		jf.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		parentLabel = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel6 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jToolBar1 = new javax.swing.JToolBar();
		newAppButton = new javax.swing.JButton();
		addSliceButton = new javax.swing.JButton();
		removeSliceButton = new javax.swing.JButton();

		jTree1.setCellRenderer(new SliceTreeRenderer());
		jTree1.setModel(model);
		jScrollPane1.setViewportView(jTree1);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jButton1.setText("Ok");

		jButton2.setText("Cancel");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(355, Short.MAX_VALUE).add(jButton1).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton2).add(4, 4, 4)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().addContainerGap().add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jButton2).add(jButton1)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(jList1);

		jLabel1.setText("Currently Assigned Agents");

		jLabel2.setText("Name:");

		jLabel3.setText("Parent:");

		name.setText("jTextField1");

		parentLabel.setText("jLabel4");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Application", "Attractor", "Repeller", "Factory", "Redundant", "Virtual" }));

		jLabel5.setText("Type:");

		jCheckBox1.setText("Enforce Policy?");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jLabel6.setText("Enforcement Policy");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
								jPanel2Layout.createSequentialGroup().add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jLabel5).add(jLabel2).add(jLabel3)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
										jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel2Layout.createSequentialGroup().add(parentLabel).add(25, 25, 25)).add(name, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217,
												Short.MAX_VALUE).add(jComboBox1, 0, 217, Short.MAX_VALUE))).add(jLabel1).add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE).add(jCheckBox1).add(jLabel6).add(jComboBox2, 0,
								259, Short.MAX_VALUE)).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2).add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel3).add(parentLabel))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
								jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel5).add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(jLabel1).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jScrollPane2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jCheckBox1).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(jLabel6).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jToolBar1.setRollover(true);

		newAppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jini/projects/neon/vertigo/management/ui/images/addsubslice.png"))); // NOI18N
		newAppButton.setToolTipText("New Application");
		newAppButton.setFocusable(false);
		newAppButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		newAppButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar1.add(newAppButton);

		addSliceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jini/projects/neon/vertigo/management/ui/images/add.png"))); // NOI18N
		addSliceButton.setToolTipText("Add Sub Slice");
		addSliceButton.setFocusable(false);
		addSliceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		addSliceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar1.add(addSliceButton);

		removeSliceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jini/projects/neon/vertigo/management/ui/images/delete.png"))); // NOI18N
		removeSliceButton.setToolTipText("Remove Selected Slice");
		removeSliceButton.setFocusable(false);
		removeSliceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		removeSliceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar1.add(removeSliceButton);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
				layout.createSequentialGroup().add(
						layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false).add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().add(
						layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
								layout.createSequentialGroup().addContainerGap().add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jCheckBox1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addSliceButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JTree jTree1;
	private javax.swing.JTextField name;
	private javax.swing.JButton newAppButton;
	private javax.swing.JLabel parentLabel;
	private javax.swing.JButton removeSliceButton;
	// End of variables declaration//GEN-END:variables

}
